# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_cpp_lib')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_cpp_lib')
    _cpp_lib = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_cpp_lib', [dirname(__file__)])
        except ImportError:
            import _cpp_lib
            return _cpp_lib
        try:
            _mod = imp.load_module('_cpp_lib', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _cpp_lib = swig_import_helper()
    del swig_import_helper
else:
    import _cpp_lib
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _cpp_lib.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _cpp_lib.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _cpp_lib.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _cpp_lib.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _cpp_lib.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _cpp_lib.SwigPyIterator_equal(self, x)

    def copy(self):
        return _cpp_lib.SwigPyIterator_copy(self)

    def next(self):
        return _cpp_lib.SwigPyIterator_next(self)

    def __next__(self):
        return _cpp_lib.SwigPyIterator___next__(self)

    def previous(self):
        return _cpp_lib.SwigPyIterator_previous(self)

    def advance(self, n):
        return _cpp_lib.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _cpp_lib.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _cpp_lib.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _cpp_lib.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _cpp_lib.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _cpp_lib.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _cpp_lib.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _cpp_lib.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class StringfloatMap(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringfloatMap, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringfloatMap, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _cpp_lib.StringfloatMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cpp_lib.StringfloatMap___nonzero__(self)

    def __bool__(self):
        return _cpp_lib.StringfloatMap___bool__(self)

    def __len__(self):
        return _cpp_lib.StringfloatMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _cpp_lib.StringfloatMap___getitem__(self, key)

    def __delitem__(self, key):
        return _cpp_lib.StringfloatMap___delitem__(self, key)

    def has_key(self, key):
        return _cpp_lib.StringfloatMap_has_key(self, key)

    def keys(self):
        return _cpp_lib.StringfloatMap_keys(self)

    def values(self):
        return _cpp_lib.StringfloatMap_values(self)

    def items(self):
        return _cpp_lib.StringfloatMap_items(self)

    def __contains__(self, key):
        return _cpp_lib.StringfloatMap___contains__(self, key)

    def key_iterator(self):
        return _cpp_lib.StringfloatMap_key_iterator(self)

    def value_iterator(self):
        return _cpp_lib.StringfloatMap_value_iterator(self)

    def __setitem__(self, *args):
        return _cpp_lib.StringfloatMap___setitem__(self, *args)

    def asdict(self):
        return _cpp_lib.StringfloatMap_asdict(self)

    def __init__(self, *args):
        this = _cpp_lib.new_StringfloatMap(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def empty(self):
        return _cpp_lib.StringfloatMap_empty(self)

    def size(self):
        return _cpp_lib.StringfloatMap_size(self)

    def swap(self, v):
        return _cpp_lib.StringfloatMap_swap(self, v)

    def begin(self):
        return _cpp_lib.StringfloatMap_begin(self)

    def end(self):
        return _cpp_lib.StringfloatMap_end(self)

    def rbegin(self):
        return _cpp_lib.StringfloatMap_rbegin(self)

    def rend(self):
        return _cpp_lib.StringfloatMap_rend(self)

    def clear(self):
        return _cpp_lib.StringfloatMap_clear(self)

    def get_allocator(self):
        return _cpp_lib.StringfloatMap_get_allocator(self)

    def count(self, x):
        return _cpp_lib.StringfloatMap_count(self, x)

    def erase(self, *args):
        return _cpp_lib.StringfloatMap_erase(self, *args)

    def find(self, x):
        return _cpp_lib.StringfloatMap_find(self, x)

    def lower_bound(self, x):
        return _cpp_lib.StringfloatMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _cpp_lib.StringfloatMap_upper_bound(self, x)
    __swig_destroy__ = _cpp_lib.delete_StringfloatMap
    __del__ = lambda self: None
StringfloatMap_swigregister = _cpp_lib.StringfloatMap_swigregister
StringfloatMap_swigregister(StringfloatMap)


def speed_landing(time, args):
    return _cpp_lib.speed_landing(time, args)
speed_landing = _cpp_lib.speed_landing

def lift_force_landing(time, args):
    return _cpp_lib.lift_force_landing(time, args)
lift_force_landing = _cpp_lib.lift_force_landing
# This file is compatible with both classic and new-style classes.


